name: .NET Desktop Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '7.0.x'

    - name: Restore NuGet packages
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release

    - name: Test
      run: dotnet test --no-build --configuration Release

    - name: Publish
      if: success()
      run: dotnet publish -c Release -o ./publish
      
    - name: Create Release
      if: success()
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v1.0.0 # Replace with your desired tag name
        release_name: Release 1.0.0 # Replace with your desired release name
        draft: false
        prerelease: false
        body: |
          Release notes for version 1.0.0:
          - Feature 1
          - Feature 2
        assets: |
          ./publish/*
